from controller.crud.crud import CRUD
from controller.crud.community import CommunityCrud
from controller.crud.user import UserCrud
from controller.crud.login import LoginCrud
from controller.crud.warning import WarningCrud
from controller.crud.dizimo_payment import DizimoPaymentCrud
from controller.crud.web_push import WebPushCrud
from controller.crud.number import NumberCrud
from controller.crud.warning_view import WarningViewCRUD
